/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurantes.view.restaurant.restaurants;

/**
 *
 * @author kemendez
 */
public class ComentariosView extends javax.swing.JPanel {

    /**
     * Creates new form ComentariosView
     */
    public ComentariosView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoClienteLabel = new javax.swing.JLabel();
        restaurantTextField = new javax.swing.JTextField();
        valoracionLabel = new javax.swing.JLabel();
        restaurantTextField1 = new javax.swing.JTextField();
        fechaLabel = new javax.swing.JLabel();
        restaurantTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        commentaryTextArea = new javax.swing.JTextArea();
        Commentary = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 107, 66));

        tipoClienteLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tipoClienteLabel.setForeground(new java.awt.Color(255, 255, 255));
        tipoClienteLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tipoClienteLabel.setText("Tipo Cliente");

        restaurantTextField.setBackground(new java.awt.Color(222, 184, 135));
        restaurantTextField.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        restaurantTextField.setForeground(new java.awt.Color(255, 255, 255));

        valoracionLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        valoracionLabel.setForeground(new java.awt.Color(255, 255, 255));
        valoracionLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        valoracionLabel.setText("Valoracion");

        restaurantTextField1.setBackground(new java.awt.Color(222, 184, 135));
        restaurantTextField1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        restaurantTextField1.setForeground(new java.awt.Color(255, 255, 255));

        fechaLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        fechaLabel.setForeground(new java.awt.Color(255, 255, 255));
        fechaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fechaLabel.setText("Fecha");

        restaurantTextField2.setBackground(new java.awt.Color(222, 184, 135));
        restaurantTextField2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        restaurantTextField2.setForeground(new java.awt.Color(255, 255, 255));

        commentaryTextArea.setBackground(new java.awt.Color(222, 184, 135));
        commentaryTextArea.setColumns(20);
        commentaryTextArea.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        commentaryTextArea.setForeground(new java.awt.Color(255, 255, 255));
        commentaryTextArea.setRows(5);
        jScrollPane1.setViewportView(commentaryTextArea);

        Commentary.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Commentary.setForeground(new java.awt.Color(255, 255, 255));
        Commentary.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Commentary.setText("Comentario");

        addButton.setBackground(new java.awt.Color(153, 107, 66));
        addButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("Añadir");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tipoClienteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(restaurantTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(valoracionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(restaurantTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fechaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(restaurantTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Commentary, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(tipoClienteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(restaurantTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(restaurantTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valoracionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(restaurantTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Commentary, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Commentary;
    public javax.swing.JButton addButton;
    public javax.swing.JTextArea commentaryTextArea;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField restaurantTextField;
    public javax.swing.JTextField restaurantTextField1;
    public javax.swing.JTextField restaurantTextField2;
    private javax.swing.JLabel tipoClienteLabel;
    private javax.swing.JLabel valoracionLabel;
    // End of variables declaration//GEN-END:variables
}
