/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurantes.view.restaurant.restaurants;

/**
 *
 * @author Curso
 */
public class Options extends javax.swing.JPanel {

    /**
     * Creates new form Options
     */
    public Options() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        restaurantButton = new javax.swing.JButton();
        restaurantButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 107, 66));

        restaurantButton.setBackground(new java.awt.Color(153, 107, 66));
        restaurantButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        restaurantButton.setForeground(new java.awt.Color(255, 255, 255));
        restaurantButton.setText("Actualizar");

        restaurantButton1.setBackground(new java.awt.Color(153, 107, 66));
        restaurantButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        restaurantButton1.setForeground(new java.awt.Color(255, 255, 255));
        restaurantButton1.setText("Añadir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(restaurantButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addComponent(restaurantButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(restaurantButton)
                    .addComponent(restaurantButton1))
                .addContainerGap(245, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton restaurantButton;
    private javax.swing.JButton restaurantButton1;
    // End of variables declaration//GEN-END:variables
}
