/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurantes.view.restaurant.restaurants;

/**
 *
 * @author kemendez
 */
public class Platillo extends javax.swing.JPanel {

    /**
     * Creates new form Platillo
     */
    public Platillo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TittleLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        restaurantLabel = new javax.swing.JLabel();
        restaurantOuputLabel = new javax.swing.JLabel();
        addCommentButton = new javax.swing.JButton();
        displayCommentButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 107, 66));

        TittleLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TittleLabel7.setForeground(new java.awt.Color(255, 255, 255));
        TittleLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TittleLabel7.setText("Descripción");

        jTextArea1.setBackground(new java.awt.Color(153, 107, 66));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        restaurantLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        restaurantLabel.setForeground(new java.awt.Color(255, 255, 255));
        restaurantLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        restaurantLabel.setText("Platillo");

        restaurantOuputLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        restaurantOuputLabel.setForeground(new java.awt.Color(255, 255, 255));
        restaurantOuputLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        addCommentButton.setBackground(new java.awt.Color(153, 107, 66));
        addCommentButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        addCommentButton.setForeground(new java.awt.Color(255, 255, 255));
        addCommentButton.setText("Añadir comentario");
        addCommentButton.setToolTipText("");
        addCommentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCommentButtonActionPerformed(evt);
            }
        });

        displayCommentButton.setBackground(new java.awt.Color(153, 107, 66));
        displayCommentButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        displayCommentButton.setForeground(new java.awt.Color(255, 255, 255));
        displayCommentButton.setText("Ver comentarios");
        displayCommentButton.setToolTipText("");
        displayCommentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayCommentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(restaurantLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(restaurantOuputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(displayCommentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TittleLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addCommentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(restaurantLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(restaurantOuputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayCommentButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TittleLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCommentButton))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addCommentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCommentButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCommentButtonActionPerformed

    private void displayCommentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayCommentButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayCommentButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TittleLabel7;
    private javax.swing.JButton addCommentButton;
    private javax.swing.JButton displayCommentButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel restaurantLabel;
    private javax.swing.JLabel restaurantOuputLabel;
    // End of variables declaration//GEN-END:variables
}
