/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurantes.view.restaurant.restaurants;

/**
 *
 * @author kemendez
 */
public class PlatilloPanel extends javax.swing.JPanel {

    /**
     * Creates new form Platillo
     */
    public PlatilloPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TittleLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        restaurantLabel = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        displayCommentButton = new javax.swing.JButton();
        addCommentButton = new javax.swing.JButton();
        platilloTextField = new javax.swing.JTextField();
        createButton = new javax.swing.JButton();
        addPlatilloRestauranteButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 107, 66));

        TittleLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TittleLabel7.setForeground(new java.awt.Color(255, 255, 255));
        TittleLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TittleLabel7.setText("Descripción");

        descriptionTextArea.setBackground(new java.awt.Color(222, 184, 135));
        descriptionTextArea.setColumns(20);
        descriptionTextArea.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        descriptionTextArea.setForeground(new java.awt.Color(255, 255, 255));
        descriptionTextArea.setRows(5);
        jScrollPane1.setViewportView(descriptionTextArea);

        restaurantLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        restaurantLabel.setForeground(new java.awt.Color(255, 255, 255));
        restaurantLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        restaurantLabel.setText("Platillo");

        deleteButton.setBackground(new java.awt.Color(153, 107, 66));
        deleteButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("Borrar");
        deleteButton.setToolTipText("");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        displayCommentButton.setBackground(new java.awt.Color(153, 107, 66));
        displayCommentButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        displayCommentButton.setForeground(new java.awt.Color(255, 255, 255));
        displayCommentButton.setText("Ver comentarios");
        displayCommentButton.setToolTipText("");
        displayCommentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayCommentButtonActionPerformed(evt);
            }
        });

        addCommentButton.setBackground(new java.awt.Color(153, 107, 66));
        addCommentButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        addCommentButton.setForeground(new java.awt.Color(255, 255, 255));
        addCommentButton.setText("Añadir comentario");
        addCommentButton.setToolTipText("");
        addCommentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCommentButtonActionPerformed(evt);
            }
        });

        platilloTextField.setBackground(new java.awt.Color(222, 184, 135));
        platilloTextField.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        platilloTextField.setForeground(new java.awt.Color(255, 255, 255));

        createButton.setBackground(new java.awt.Color(153, 107, 66));
        createButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        createButton.setForeground(new java.awt.Color(255, 255, 255));
        createButton.setText("Crear Nuevo");
        createButton.setToolTipText("");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        addPlatilloRestauranteButton.setBackground(new java.awt.Color(153, 107, 66));
        addPlatilloRestauranteButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        addPlatilloRestauranteButton.setForeground(new java.awt.Color(255, 255, 255));
        addPlatilloRestauranteButton.setText("Añadir a restaurante");
        addPlatilloRestauranteButton.setToolTipText("");
        addPlatilloRestauranteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPlatilloRestauranteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TittleLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(restaurantLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(platilloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayCommentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addPlatilloRestauranteButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addCommentButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(restaurantLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(platilloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(displayCommentButton)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(TittleLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(addCommentButton)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(createButton)
                        .addGap(18, 18, 18)
                        .addComponent(addPlatilloRestauranteButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void displayCommentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayCommentButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayCommentButtonActionPerformed

    private void addCommentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCommentButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCommentButtonActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createButtonActionPerformed

    private void addPlatilloRestauranteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPlatilloRestauranteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addPlatilloRestauranteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TittleLabel7;
    public javax.swing.JButton addCommentButton;
    public javax.swing.JButton addPlatilloRestauranteButton;
    public javax.swing.JButton createButton;
    public javax.swing.JButton deleteButton;
    public javax.swing.JTextArea descriptionTextArea;
    public javax.swing.JButton displayCommentButton;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField platilloTextField;
    private javax.swing.JLabel restaurantLabel;
    // End of variables declaration//GEN-END:variables
}
