/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurantes.view.restaurant.restaurants;

/**
 *
 * @author kemendez
 */
public class Restaurantes extends javax.swing.JPanel {

    /**
     * Creates new form Restaurantes
     */
    public Restaurantes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dietButton3 = new javax.swing.JButton();
        goodForButton1 = new javax.swing.JButton();
        restaurantOuputLabel = new javax.swing.JLabel();
        restaurantLabel = new javax.swing.JLabel();
        countryLabel = new javax.swing.JLabel();
        countryOutptLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        cityOutPutLabel = new javax.swing.JLabel();
        TittleLabel6 = new javax.swing.JLabel();
        priceOutputLabel = new javax.swing.JLabel();
        establishmentLabel = new javax.swing.JLabel();
        establishmentOutputLabel = new javax.swing.JLabel();
        TittleLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcionTextArea = new javax.swing.JTextArea();
        cookButton = new javax.swing.JButton();
        timeButton = new javax.swing.JButton();
        dietButton = new javax.swing.JButton();
        foodsButton = new javax.swing.JButton();
        goodForButton2 = new javax.swing.JButton();
        comeInButton = new javax.swing.JButton();
        comeInButton1 = new javax.swing.JButton();

        dietButton3.setBackground(new java.awt.Color(153, 107, 66));
        dietButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dietButton3.setForeground(new java.awt.Color(255, 255, 255));
        dietButton3.setText("Bueno para...");
        dietButton3.setToolTipText("");
        dietButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dietButton3ActionPerformed(evt);
            }
        });

        goodForButton1.setBackground(new java.awt.Color(153, 107, 66));
        goodForButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        goodForButton1.setForeground(new java.awt.Color(255, 255, 255));
        goodForButton1.setText("Bueno para...");
        goodForButton1.setToolTipText("");
        goodForButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goodForButton1ActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(153, 107, 66));

        restaurantOuputLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        restaurantOuputLabel.setForeground(new java.awt.Color(255, 255, 255));
        restaurantOuputLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        restaurantLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        restaurantLabel.setForeground(new java.awt.Color(255, 255, 255));
        restaurantLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        restaurantLabel.setText("Restaurante");

        countryLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        countryLabel.setForeground(new java.awt.Color(255, 255, 255));
        countryLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        countryLabel.setText("País");

        countryOutptLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        countryOutptLabel.setForeground(new java.awt.Color(255, 255, 255));
        countryOutptLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        cityLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cityLabel.setForeground(new java.awt.Color(255, 255, 255));
        cityLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cityLabel.setText("Ciudad");

        cityOutPutLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cityOutPutLabel.setForeground(new java.awt.Color(255, 255, 255));
        cityOutPutLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        TittleLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TittleLabel6.setForeground(new java.awt.Color(255, 255, 255));
        TittleLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TittleLabel6.setText("Precios");

        priceOutputLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        priceOutputLabel.setForeground(new java.awt.Color(255, 255, 255));
        priceOutputLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        establishmentLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        establishmentLabel.setForeground(new java.awt.Color(255, 255, 255));
        establishmentLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        establishmentLabel.setText("Establecimiento");

        establishmentOutputLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        establishmentOutputLabel.setForeground(new java.awt.Color(255, 255, 255));
        establishmentOutputLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        TittleLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TittleLabel7.setForeground(new java.awt.Color(255, 255, 255));
        TittleLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TittleLabel7.setText("Descrition");

        descripcionTextArea.setBackground(new java.awt.Color(153, 107, 66));
        descripcionTextArea.setColumns(20);
        descripcionTextArea.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        descripcionTextArea.setForeground(new java.awt.Color(255, 255, 255));
        descripcionTextArea.setRows(5);
        jScrollPane1.setViewportView(descripcionTextArea);

        cookButton.setBackground(new java.awt.Color(153, 107, 66));
        cookButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cookButton.setForeground(new java.awt.Color(255, 255, 255));
        cookButton.setText("Cocina");
        cookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cookButtonActionPerformed(evt);
            }
        });

        timeButton.setBackground(new java.awt.Color(153, 107, 66));
        timeButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        timeButton.setForeground(new java.awt.Color(255, 255, 255));
        timeButton.setText("Tiempos");
        timeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeButtonActionPerformed(evt);
            }
        });

        dietButton.setBackground(new java.awt.Color(153, 107, 66));
        dietButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dietButton.setForeground(new java.awt.Color(255, 255, 255));
        dietButton.setText("Dietas");
        dietButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dietButtonActionPerformed(evt);
            }
        });

        foodsButton.setBackground(new java.awt.Color(153, 107, 66));
        foodsButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        foodsButton.setForeground(new java.awt.Color(255, 255, 255));
        foodsButton.setText("Platillos");
        foodsButton.setToolTipText("");
        foodsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodsButtonActionPerformed(evt);
            }
        });

        goodForButton2.setBackground(new java.awt.Color(153, 107, 66));
        goodForButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        goodForButton2.setForeground(new java.awt.Color(255, 255, 255));
        goodForButton2.setText("Bueno para...");
        goodForButton2.setToolTipText("");
        goodForButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goodForButton2ActionPerformed(evt);
            }
        });

        comeInButton.setBackground(new java.awt.Color(153, 107, 66));
        comeInButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        comeInButton.setForeground(new java.awt.Color(255, 255, 255));
        comeInButton.setText("Llegada");
        comeInButton.setToolTipText("");
        comeInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comeInButtonActionPerformed(evt);
            }
        });

        comeInButton1.setBackground(new java.awt.Color(153, 107, 66));
        comeInButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        comeInButton1.setForeground(new java.awt.Color(255, 255, 255));
        comeInButton1.setText("Actualizar");
        comeInButton1.setToolTipText("");
        comeInButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comeInButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(restaurantLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(restaurantOuputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(dietButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(countryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(establishmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TittleLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(countryOutptLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(establishmentOutputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(priceOutputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(cityOutPutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(goodForButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(foodsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comeInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TittleLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(329, 329, 329)
                        .addComponent(comeInButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dietButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(restaurantLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(restaurantOuputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cookButton)
                        .addGap(6, 6, 6)
                        .addComponent(timeButton)
                        .addGap(5, 5, 5)
                        .addComponent(goodForButton2)
                        .addGap(6, 6, 6)
                        .addComponent(foodsButton)
                        .addGap(6, 6, 6)
                        .addComponent(comeInButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(countryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(cityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(establishmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(TittleLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(countryOutptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(cityOutPutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(establishmentOutputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(priceOutputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(TittleLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comeInButton1))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cookButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cookButtonActionPerformed

    private void timeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeButtonActionPerformed

    private void dietButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dietButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dietButtonActionPerformed

    private void foodsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foodsButtonActionPerformed

    private void dietButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dietButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dietButton3ActionPerformed

    private void goodForButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goodForButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goodForButton1ActionPerformed

    private void goodForButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goodForButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goodForButton2ActionPerformed

    private void comeInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comeInButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comeInButtonActionPerformed

    private void comeInButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comeInButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comeInButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TittleLabel6;
    private javax.swing.JLabel TittleLabel7;
    private javax.swing.JLabel cityLabel;
    public javax.swing.JLabel cityOutPutLabel;
    public javax.swing.JButton comeInButton;
    public javax.swing.JButton comeInButton1;
    public javax.swing.JButton cookButton;
    private javax.swing.JLabel countryLabel;
    public javax.swing.JLabel countryOutptLabel;
    public javax.swing.JTextArea descripcionTextArea;
    public javax.swing.JButton dietButton;
    private javax.swing.JButton dietButton3;
    private javax.swing.JLabel establishmentLabel;
    public javax.swing.JLabel establishmentOutputLabel;
    public javax.swing.JButton foodsButton;
    private javax.swing.JButton goodForButton1;
    public javax.swing.JButton goodForButton2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel priceOutputLabel;
    private javax.swing.JLabel restaurantLabel;
    public javax.swing.JLabel restaurantOuputLabel;
    public javax.swing.JButton timeButton;
    // End of variables declaration//GEN-END:variables
}
