/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurantes.view.restaurant;

import java.awt.BorderLayout;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import restaurantes.controller.restaurante.ControllerRestaurantItem;
import restaurantes.render.PanelCellEditorRenderer;
import restaurantes.render.PanelTableModel;


public class DisplayPanel extends javax.swing.JPanel {

   private JTable CompTable = null;
   private PanelTableModel CompModel = null;
   
    public DisplayPanel() {
        initComponents();
    }
    
    public void ShowItemList(List<JPanel> paneList) {
        CompModel = new PanelTableModel();
        
        for (int i = 0; i < paneList.size(); i++) {
            CompModel.addRow(paneList.get(i));
        }
        
        JTable table = new JTable(CompModel);
        table.setRowHeight(paneList.get(0).getPreferredSize().height);
        table.setTableHeader(null);
        PanelCellEditorRenderer PanelCellEditorRenderer = new PanelCellEditorRenderer();
        table.setDefaultRenderer(Object.class, PanelCellEditorRenderer);
        table.setDefaultEditor(Object.class, PanelCellEditorRenderer);
        
        CompTable = table;
        
        JScrollPane CompTableScrollpane = new JScrollPane(CompTable, JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,
                JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);

        this.add(CompTableScrollpane, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(153, 107, 66));
        setLayout(new java.awt.GridLayout(1, 0));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
