/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurantes.view.restaurant;

/**
 *
 * @author Curso
 */
public class Restaurant extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public Restaurant() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        foodsButton = new javax.swing.JButton();
        optionsLabel = new javax.swing.JLabel();
        restaurantButton = new javax.swing.JButton();
        collaboratorsButton = new javax.swing.JButton();
        commentsButton = new javax.swing.JButton();
        othersButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 107, 66));
        setPreferredSize(new java.awt.Dimension(880, 500));

        foodsButton.setBackground(new java.awt.Color(153, 107, 66));
        foodsButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        foodsButton.setForeground(new java.awt.Color(255, 255, 255));
        foodsButton.setText("Platillos");

        optionsLabel.setBackground(new java.awt.Color(153, 107, 66));
        optionsLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        optionsLabel.setForeground(new java.awt.Color(255, 255, 255));
        optionsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        optionsLabel.setText("Opciones");

        restaurantButton.setBackground(new java.awt.Color(153, 107, 66));
        restaurantButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        restaurantButton.setForeground(new java.awt.Color(255, 255, 255));
        restaurantButton.setText("Restaurantes");

        collaboratorsButton.setBackground(new java.awt.Color(153, 107, 66));
        collaboratorsButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        collaboratorsButton.setForeground(new java.awt.Color(255, 255, 255));
        collaboratorsButton.setText("Colaboradores");

        commentsButton.setBackground(new java.awt.Color(153, 107, 66));
        commentsButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        commentsButton.setForeground(new java.awt.Color(255, 255, 255));
        commentsButton.setText("Comentarios");

        othersButton.setBackground(new java.awt.Color(153, 107, 66));
        othersButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        othersButton.setForeground(new java.awt.Color(255, 255, 255));
        othersButton.setText("Otros");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foodsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(restaurantButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(collaboratorsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(commentsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(othersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(689, 689, 689))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(optionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addComponent(restaurantButton)
                .addGap(18, 18, 18)
                .addComponent(foodsButton)
                .addGap(18, 18, 18)
                .addComponent(collaboratorsButton)
                .addGap(18, 18, 18)
                .addComponent(commentsButton)
                .addGap(18, 18, 18)
                .addComponent(othersButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton collaboratorsButton;
    private javax.swing.JButton commentsButton;
    private javax.swing.JButton foodsButton;
    private javax.swing.JLabel optionsLabel;
    private javax.swing.JButton othersButton;
    private javax.swing.JButton restaurantButton;
    // End of variables declaration//GEN-END:variables
}
